/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as coreHttp from "@azure/core-http";
import { Candidates, Clients, Jobs, Schema, Todos } from "./operations";
import { DoverOnsiteCodingChallengeBackendAPIContext } from "./doverOnsiteCodingChallengeBackendAPIContext";
import { DoverOnsiteCodingChallengeBackendAPIOptionalParams } from "./models";

export class DoverOnsiteCodingChallengeBackendAPI extends DoverOnsiteCodingChallengeBackendAPIContext {
  /**
   * Initializes a new instance of the DoverOnsiteCodingChallengeBackendAPI class.
   * @param credentials Subscription credentials which uniquely identify client subscription.
   * @param options The parameter options
   */
  constructor(
    credentials: coreHttp.TokenCredential | coreHttp.ServiceClientCredentials,
    options?: DoverOnsiteCodingChallengeBackendAPIOptionalParams
  ) {
    super(credentials, options);
    this.candidates = new Candidates(this);
    this.clients = new Clients(this);
    this.jobs = new Jobs(this);
    this.schema = new Schema(this);
    this.todos = new Todos(this);
  }

  candidates: Candidates;
  clients: Clients;
  jobs: Jobs;
  schema: Schema;
  todos: Todos;
}
