# Generated by Django 3.1.4 on 2021-01-16 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20210112_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='client.client'),
        ),
    ]
