# Generated by Django 3.1.4 on 2021-01-18 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20210116_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDraft',
            fields=[
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='client.job')),
            ],
        ),
    ]
