# Generated by Django 3.1.4 on 2021-01-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_jobdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hasDraft',
            field=models.BooleanField(default=False),
        ),
    ]
