# Generated by Django 3.1.4 on 2021-01-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_job_hasdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='templateDraft',
            field=models.TextField(null=True),
        ),
    ]
