# Generated by Django 3.1.4 on 2021-01-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20210118_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='subject',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.DeleteModel(
            name='JobDraft',
        ),
    ]
