# Generated by Django 3.1.4 on 2021-01-19 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_auto_20210118_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='subject',
        ),
    ]
