# Generated by Django 3.1.4 on 2021-02-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('years_experience', models.DecimalField(decimal_places=2, max_digits=5)),
                ('custom', models.TextField()),
            ],
        ),
    ]
