# Generated by Django 3.1.4 on 2020-12-29 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Candidate',
        ),
    ]
