# Generated by Django 3.1.4 on 2021-01-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_auto_20201229_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='custom',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
