# Generated by Django 3.1.4 on 2021-01-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_candidate_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='years_experience',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
